language: java
jdk:
- oraclejdk8
install: travis_wait mvn install -B -V
env: MAVEN_OPTS="-XX:MaxPermSize=512m"

## Get the project version
before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: PKjFgJuhYSLte+vbNlekCi6jbxJfuJ4LLojoAeSse1BahPKIJ3RtgDdm6VjwJ/byaBjiWi5AoeC37nuzv9Z8L2r07OaCQu707OlmFemzsJHCf/14LyV//P5GL1hJ5n0HipE7C0rnW1Ai8fdXCwCMJ/FPKJakh7ETqHN/I+HX3KtVQYoD2CJ6O6eJis/dT/AHm/wlijySV4JG4SfTuvZ4D0u/SnH26VxfxAeQ58DM688ZHgmc96k58Xw1M1WQbH/cqAb741nszvldjMzaK30wCfhfrHyXhlaiYzubogegQLbgF8jVeiJH101+oEhm8x8NcWBuvR7ZU+lbPqS8F/GmqWOh7FLPx7mUvrn1VGYPxxCIWFlJPBPlhaySc/w9mBLF5eFRG0Oy3As+ku/deafjztwtnXJT5d5dZqHmmMbqEjuy9YV4hw54E6ZX0UOctDLmkFiF9IqfG8TIjhOP/IpeQF+UkedKtDEjmWn9tsZ579BCRv8JG4UvBPvCsUcsr7aRn2KwHP0VBlSDyvQU1FVEnQhFU3OG0GErVXwW5wQtDsEEZ5M2+uzwrgitvjXNHTm/iECuWW1Jq0HnhMOFJa+NpuPfGv9KxglYIesCJfoRe74rpeMe31L2iA/CFaPl/hCsU3IT7r6d0RpUG9bw9hy4E+ZUuiaa2JcqeBZF26GUclY=
  file:
    - MapCore/target/MapCore-$project_version.jar
    - SurveyorCore/target/SurveyorCore-$project_version.jar
    - SurveyorSimpleDemoApp/target/SurveyorSimpleDemoApp-$project_version.war
  skip_cleanup: true
  on:
    branch: master
    repo: WorldwideAntimalarialResistanceNetwork/WWARN-Maps-Surveyor
  name: $project_version

cache:
    directories:
        - ~/.m2/repository
